name: Run Forecasting and Upload Predictions

on:
  workflow_dispatch:  # Trigger manually for now

jobs:
  forecast:
    runs-on: ubuntu-latest
    env:
      HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME }}
      HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # -------- Current Predictions --------
      - name: Generate Current Predictions (Lag28, TopK, PCA)
        run: |
          python src/inference/current_prediction_lag28.py
          python src/inference/current_prediction_topk.py
          python src/inference/current_prediction_pca.py

      # -------- Future Forecasts --------
      - name: Generate Future Forecasts (Lag28, TopK, PCA)
        run: |
          python src/inference/forecast_future_lag28.py
          python src/inference/forecast_future_topk.py
          python src/inference/forecast_future_pca.py

      # -------- Upload All to Hopsworks --------
      - name: Upload All Predictions to Hopsworks
        run: |
          python src/upload/upload_to_hopsworks_inference.py
